import type { CreateArticleUseCase } from "#/core/article/application/port/in/CreateArticleUseCase";
import type { DeleteArticleUseCase } from "#/core/article/application/port/in/DeleteArticleUseCase";
import type { GetArticleBySlugUseCase } from "#/core/article/application/port/in/GetArticleBySlugUseCase";
import type { GetArticleUseCase } from "#/core/article/application/port/in/GetArticleUseCase";
import type { GetNextArticleSeqUseCase } from "#/core/article/application/port/in/GetNextArticleSeqUseCase";
import type { GetPublishedArticleBySlugUseCase } from "#/core/article/application/port/in/GetPublishedArticleBySlugUseCase";
import type { GetPublishedArticleNeighborsUseCase } from "#/core/article/application/port/in/GetPublishedArticleNeighborsUseCase";
import type { ListArticlesByCategoryUseCase } from "#/core/article/application/port/in/ListArticlesByCategoryUseCase";
import type { ListArticlesUseCase } from "#/core/article/application/port/in/ListArticlesUseCase";
import type { ListPublishedArticlesUseCase } from "#/core/article/application/port/in/ListPublishedArticlesUseCase";
import type { UpdateArticleUseCase } from "#/core/article/application/port/in/UpdateArticleUseCase";
import type { ArticleCommandPort } from "#/core/article/application/port/out/ArticleCommandPort";
import type { ArticleQueryPort } from "#/core/article/application/port/out/ArticleQueryPort";
import type { SignOwnerSessionUseCase } from "#/core/auth/application/port/in/SignOwnerSessionUseCase";
import type { VerifyGoogleOwnerUseCase } from "#/core/auth/application/port/in/VerifyGoogleOwnerUseCase";
import type { VerifyOwnerSessionUseCase } from "#/core/auth/application/port/in/VerifyOwnerSessionUseCase";
import type { GoogleIdentityPort } from "#/core/auth/application/port/out/GoogleIdentityPort";
import type { SessionTokenPort } from "#/core/auth/application/port/out/SessionTokenPort";
import type { OwnerAuthConfig } from "#/core/auth/config/OwnerAuthConfig";
import type { CreateMusingUseCase } from "#/core/musings/application/port/in/CreateMusingUseCase";
import type { DeleteMusingUseCase } from "#/core/musings/application/port/in/DeleteMusingUseCase";
import type { GetMusingUseCase } from "#/core/musings/application/port/in/GetMusingUseCase";
import type { ListMusingsUseCase } from "#/core/musings/application/port/in/ListMusingsUseCase";
import type { ListPublishedMusingsUseCase } from "#/core/musings/application/port/in/ListPublishedMusingsUseCase";
import type { UpdateMusingUseCase } from "#/core/musings/application/port/in/UpdateMusingUseCase";
import type { MusingsCommandPort } from "#/core/musings/application/port/out/MusingsCommandPort";
import type { MusingsQueryPort } from "#/core/musings/application/port/out/MusingsQueryPort";

export type UseCaseBeans = {
	VerifyGoogleOwnerUseCase: VerifyGoogleOwnerUseCase;
	SignOwnerSessionUseCase: SignOwnerSessionUseCase;
	VerifyOwnerSessionUseCase: VerifyOwnerSessionUseCase;
	CreateArticleUseCase: CreateArticleUseCase;
	GetArticleUseCase: GetArticleUseCase;
	GetArticleBySlugUseCase: GetArticleBySlugUseCase;
	GetNextArticleSeqUseCase: GetNextArticleSeqUseCase;
	ListArticlesUseCase: ListArticlesUseCase;
	ListArticlesByCategoryUseCase: ListArticlesByCategoryUseCase;
	ListPublishedArticlesUseCase: ListPublishedArticlesUseCase;
	GetPublishedArticleBySlugUseCase: GetPublishedArticleBySlugUseCase;
	GetPublishedArticleNeighborsUseCase: GetPublishedArticleNeighborsUseCase;
	UpdateArticleUseCase: UpdateArticleUseCase;
	DeleteArticleUseCase: DeleteArticleUseCase;
	CreateMusingUseCase: CreateMusingUseCase;
	GetMusingUseCase: GetMusingUseCase;
	ListMusingsUseCase: ListMusingsUseCase;
	ListPublishedMusingsUseCase: ListPublishedMusingsUseCase;
	UpdateMusingUseCase: UpdateMusingUseCase;
	DeleteMusingUseCase: DeleteMusingUseCase;
};

export type OutboundBeans = {
	OwnerAuthConfig: OwnerAuthConfig;
	GoogleIdentityPort: GoogleIdentityPort;
	SessionTokenPort: SessionTokenPort;
	ArticleCommandPort: ArticleCommandPort;
	ArticleQueryPort: ArticleQueryPort;
	MusingsCommandPort: MusingsCommandPort;
	MusingsQueryPort: MusingsQueryPort;
};

export type Beans = UseCaseBeans & OutboundBeans;
