import './globals.css';
import React from 'react';
import HeaderButton from '@/app/common/components/HeaderButton';
import Link from 'next/link';
import clsx from 'clsx';
import { inconsolata } from '@/app/common/fonts/inconsolata';
import { suit } from '@/app/common/fonts/suit';
import CategoriesOnClientContainer from '@/app/common/containers/CategoriesOnClientContainer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const categories = ['about', 'blog', 'daily', 'musings', 'places'];

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={clsx(suit.className, 'break-keep')}>
        <header>
          <div className={'mb-2 mt-6 flex justify-center sm:mb-5 sm:mt-10'}>
            <div>
              <Link href="/">
                <HeaderButton className={clsx(inconsolata.className, 'uppercase tracking-[3px]')}>
                  Myeongjae Kim
                </HeaderButton>
              </Link>
            </div>
          </div>
          <div className={'flex justify-center'}>
            <CategoriesOnClientContainer categories={categories} />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
