/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/terraceNeutral.ts
 * Command: astryx theme build src/themes/terraceNeutral.ts
 * Generated: 2026-07-14T06:51:36.117Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const terraceNeutralTheme: DefinedTheme;
