/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as MusingsRouteImport } from './routes/musings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminPlacesRouteImport } from './routes/admin.places'
import { Route as AdminDailyRouteImport } from './routes/admin.daily'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminDailyNewRouteImport } from './routes/admin.daily.new'
import { Route as AdminDailyArticleIdRouteImport } from './routes/admin.daily.$articleId'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogArticleIdRouteImport } from './routes/admin.blog.$articleId'
import { Route as DailyYearMonthDaySlugRouteImport } from './routes/daily_.$year.$month.$day.$slug'
import { Route as BlogYearMonthDaySlugRouteImport } from './routes/blog_.$year.$month.$day.$slug'

const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const MusingsRoute = MusingsRouteImport.update({
  id: '/musings',
  path: '/musings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlacesRoute = AdminPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDailyRoute = AdminDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDailyNewRoute = AdminDailyNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminDailyRoute,
} as any)
const AdminDailyArticleIdRoute = AdminDailyArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => AdminDailyRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogArticleIdRoute = AdminBlogArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => AdminBlogRoute,
} as any)
const DailyYearMonthDaySlugRoute = DailyYearMonthDaySlugRouteImport.update({
  id: '/daily_/$year/$month/$day/$slug',
  path: '/daily/$year/$month/$day/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogYearMonthDaySlugRoute = BlogYearMonthDaySlugRouteImport.update({
  id: '/blog_/$year/$month/$day/$slug',
  path: '/blog/$year/$month/$day/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/daily': typeof DailyRoute
  '/login': typeof LoginRoute
  '/musings': typeof MusingsRoute
  '/places': typeof PlacesRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/daily': typeof AdminDailyRouteWithChildren
  '/admin/places': typeof AdminPlacesRoute
  '/admin/blog/$articleId': typeof AdminBlogArticleIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/daily/$articleId': typeof AdminDailyArticleIdRoute
  '/admin/daily/new': typeof AdminDailyNewRoute
  '/blog/$year/$month/$day/$slug': typeof BlogYearMonthDaySlugRoute
  '/daily/$year/$month/$day/$slug': typeof DailyYearMonthDaySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/daily': typeof DailyRoute
  '/login': typeof LoginRoute
  '/musings': typeof MusingsRoute
  '/places': typeof PlacesRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/daily': typeof AdminDailyRouteWithChildren
  '/admin/places': typeof AdminPlacesRoute
  '/admin/blog/$articleId': typeof AdminBlogArticleIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/daily/$articleId': typeof AdminDailyArticleIdRoute
  '/admin/daily/new': typeof AdminDailyNewRoute
  '/blog/$year/$month/$day/$slug': typeof BlogYearMonthDaySlugRoute
  '/daily/$year/$month/$day/$slug': typeof DailyYearMonthDaySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/daily': typeof DailyRoute
  '/login': typeof LoginRoute
  '/musings': typeof MusingsRoute
  '/places': typeof PlacesRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/daily': typeof AdminDailyRouteWithChildren
  '/admin/places': typeof AdminPlacesRoute
  '/admin/blog/$articleId': typeof AdminBlogArticleIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/daily/$articleId': typeof AdminDailyArticleIdRoute
  '/admin/daily/new': typeof AdminDailyNewRoute
  '/blog_/$year/$month/$day/$slug': typeof BlogYearMonthDaySlugRoute
  '/daily_/$year/$month/$day/$slug': typeof DailyYearMonthDaySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/daily'
    | '/login'
    | '/musings'
    | '/places'
    | '/admin/blog'
    | '/admin/daily'
    | '/admin/places'
    | '/admin/blog/$articleId'
    | '/admin/blog/new'
    | '/admin/daily/$articleId'
    | '/admin/daily/new'
    | '/blog/$year/$month/$day/$slug'
    | '/daily/$year/$month/$day/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/daily'
    | '/login'
    | '/musings'
    | '/places'
    | '/admin/blog'
    | '/admin/daily'
    | '/admin/places'
    | '/admin/blog/$articleId'
    | '/admin/blog/new'
    | '/admin/daily/$articleId'
    | '/admin/daily/new'
    | '/blog/$year/$month/$day/$slug'
    | '/daily/$year/$month/$day/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/daily'
    | '/login'
    | '/musings'
    | '/places'
    | '/admin/blog'
    | '/admin/daily'
    | '/admin/places'
    | '/admin/blog/$articleId'
    | '/admin/blog/new'
    | '/admin/daily/$articleId'
    | '/admin/daily/new'
    | '/blog_/$year/$month/$day/$slug'
    | '/daily_/$year/$month/$day/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  DailyRoute: typeof DailyRoute
  LoginRoute: typeof LoginRoute
  MusingsRoute: typeof MusingsRoute
  PlacesRoute: typeof PlacesRoute
  BlogYearMonthDaySlugRoute: typeof BlogYearMonthDaySlugRoute
  DailyYearMonthDaySlugRoute: typeof DailyYearMonthDaySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musings': {
      id: '/musings'
      path: '/musings'
      fullPath: '/musings'
      preLoaderRoute: typeof MusingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/places': {
      id: '/admin/places'
      path: '/places'
      fullPath: '/admin/places'
      preLoaderRoute: typeof AdminPlacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/daily': {
      id: '/admin/daily'
      path: '/daily'
      fullPath: '/admin/daily'
      preLoaderRoute: typeof AdminDailyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/daily/new': {
      id: '/admin/daily/new'
      path: '/new'
      fullPath: '/admin/daily/new'
      preLoaderRoute: typeof AdminDailyNewRouteImport
      parentRoute: typeof AdminDailyRoute
    }
    '/admin/daily/$articleId': {
      id: '/admin/daily/$articleId'
      path: '/$articleId'
      fullPath: '/admin/daily/$articleId'
      preLoaderRoute: typeof AdminDailyArticleIdRouteImport
      parentRoute: typeof AdminDailyRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/$articleId': {
      id: '/admin/blog/$articleId'
      path: '/$articleId'
      fullPath: '/admin/blog/$articleId'
      preLoaderRoute: typeof AdminBlogArticleIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/daily_/$year/$month/$day/$slug': {
      id: '/daily_/$year/$month/$day/$slug'
      path: '/daily/$year/$month/$day/$slug'
      fullPath: '/daily/$year/$month/$day/$slug'
      preLoaderRoute: typeof DailyYearMonthDaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$year/$month/$day/$slug': {
      id: '/blog_/$year/$month/$day/$slug'
      path: '/blog/$year/$month/$day/$slug'
      fullPath: '/blog/$year/$month/$day/$slug'
      preLoaderRoute: typeof BlogYearMonthDaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogArticleIdRoute: typeof AdminBlogArticleIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogArticleIdRoute: AdminBlogArticleIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminDailyRouteChildren {
  AdminDailyArticleIdRoute: typeof AdminDailyArticleIdRoute
  AdminDailyNewRoute: typeof AdminDailyNewRoute
}

const AdminDailyRouteChildren: AdminDailyRouteChildren = {
  AdminDailyArticleIdRoute: AdminDailyArticleIdRoute,
  AdminDailyNewRoute: AdminDailyNewRoute,
}

const AdminDailyRouteWithChildren = AdminDailyRoute._addFileChildren(
  AdminDailyRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminDailyRoute: typeof AdminDailyRouteWithChildren
  AdminPlacesRoute: typeof AdminPlacesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminDailyRoute: AdminDailyRouteWithChildren,
  AdminPlacesRoute: AdminPlacesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  DailyRoute: DailyRoute,
  LoginRoute: LoginRoute,
  MusingsRoute: MusingsRoute,
  PlacesRoute: PlacesRoute,
  BlogYearMonthDaySlugRoute: BlogYearMonthDaySlugRoute,
  DailyYearMonthDaySlugRoute: DailyYearMonthDaySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
